using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SecureApp.Models;
using Google.Authenticator;

namespace SecureApp.Controllers
{
    public class HomeController : Controller
    {

        private const string key = "osiuvhnr09f7342j";


        public ActionResult Index()
        {
            //Are you logged in? if not, redirect to /Login
            //Remember me function?


            return View();
        }
        // GET: Home
        public ActionResult Login()
        {
            return View();
        }




        public ActionResult Dashboard()
        {
            //Display of your passwords


            return View();
        }

        //This method will be HttpPost. In this method, we will first verify user-provided 
        //credential from the database.Then if the user is valid, then we will generate 
        //Two Factor authentication setup code for use in the Google Authenticator mobile
        //app for setup account.

        [HttpPost]
        public ActionResult Login(LoginModel login)
        {
            string message = "";
            bool status = false;
            //check UserName and password form our database here
            if (login.UserName == "Admin" && login.Password == "12345") // Admin as user name and 12345 as Password
            {
                status = true;
                message = "Two Factor Authentication Verification";
                Session["UserName"] = login.UserName;
                //Two Factor Authentication Setup
                TwoFactorAuthenticator TwoFacAuth = new TwoFactorAuthenticator();
                string UserUniqueKey = (login.UserName + key);
                Session["UserUniqueKey"] = UserUniqueKey;
                var setupInfo = TwoFacAuth.GenerateSetupCode("Dot Net Detail", login.UserName, UserUniqueKey, 300, 300);
                ViewBag.BarcodeImageUrl = setupInfo.QrCodeSetupImageUrl;
                ViewBag.SetupCode = setupInfo.ManualEntryKey;
            }
            else
            {
                message = "The entered credentials are invalid";
            }
            ViewBag.Message = message;
            ViewBag.Status = status;
            return View();
        }


        //In this action method, authorized user will be redirected to a page after successful login.
        public ActionResult UserProfile()
        {
            if (Session["Username"] == null || Session["IsValidTwoFactorAuthentication"] == null || !(bool)Session["IsValidTwoFactorAuthentication"])
            {
                return RedirectToAction("Login");
            }
            ViewBag.Message = "Welcome to Mr. " + Session["Username"].ToString();
            return View();
        }

        //This action method will verify two factor authentication token generated by Google Authenticator
        //mobile application. And then the user will be redirected to the authorized area of the application.
        public ActionResult TwoFactorAuthenticate()
        {
            var token = Request["CodeDigit"];
            TwoFactorAuthenticator TwoFacAuth = new TwoFactorAuthenticator();
            string UserUniqueKey = Session["UserUniqueKey"].ToString();
            bool isValid = TwoFacAuth.ValidateTwoFactorPIN(UserUniqueKey, token);
            if (isValid)
            {
                Session["IsValidTwoFactorAuthentication"] = true;
                return RedirectToAction("Dashboard", "Home");
            }
            return RedirectToAction("Login", "Home");
        }


    }
}